extern int gettables();
extern int testchario(word modstr);
extern int getcpt();
extern int getdpt();
extern int getthdstr(word *dptr);
extern int getnxtthd(word *nxtthd, word thd);
extern int btcom(COMTABL *compart, word modstr);
extern int btchario(CHARTABL *chrmod, word modstr);
extern int btdiskio(DISKTABL *diskmod, word modstr);
extern int btxmode(CHARDEV *chrentry);
extern int btchrtbl(CHARDEV *chrentry);
extern int getnode(word modstr);
extern int btmode(FLOPDEV *flpentry);
extern int getxmadr(word *adr, word modstr);
extern int getctadr(word *adr, word modstr, byte phydevnum);
extern int getmadr(word *adr, word modstr);
extern void btdsize(FLOPDEV *flpentry);
extern void btdrvcontr(FLOPDEV *flpentry);
extern void btsteprt(FLOPDEV *flpentry);
extern void btmedia(FLOPDEV *flpentry);
extern void btmediaft(FLOPDEV *flpentry);
extern void btsides(FLOPCHAR *flpchar, byte *modebyt);
extern void bttrkden(FLOPCHAR *flpchar, byte *modebyt);
extern void btrecden(FLOPCHAR *flpchar, byte *modebyt);
extern int testbit(byte *array, ushort bitpos);
