extern void setdiskio(DISKTABL *maindsk, char *filename);
extern void cpydsk(DISKTABL *dsk1, DISKTABL *dsk2);
extern void prtdhd(DISKTABL *dskentry, bool confg);
extern void prtdvar(DISKTABL *dskentry, bool confg);
extern int getdfld(DISKTABL *dskentry, bool confg);
extern void prtdmsg(DISKTABL *dskentry, bool confg);
extern void lstfmt(FLOPDEV *flpentry);
extern int dsidfld(FLOPDEV *flpentry);
extern int dtrkfld(FLOPDEV *flpentry);
extern int drecfld(FLOPDEV *flpentry);
extern int steprtfld(FLOPDEV *flpentry);
extern int msidfld(FLOPDEV *flpentry);
extern int mtrkfld(FLOPDEV *flpentry);
extern int mrecfld(FLOPDEV *flpentry);
extern int mformat(FLOPDEV *flpentry);
extern int searchfmt(char *fmtstr);
extern int cmpfmt(char *fmtstr, char *tblpt);
extern int notsupmsg();
extern void prtfld(DISKTABL *dskentry);
extern void prtphydrv(DISKTABL *dskentry);
extern void prtdsiz(DISKTABL *dskentry);
extern void prtdrvlt(DISKTABL *dskentry);
extern int searchlp(ushort devnum);
extern void prtsides(FLOPCHAR *flpchar);
extern void prttrkden(FLOPCHAR *flpchar);
extern void prtrecden(FLOPCHAR *flpchar);
extern void prtstrt(DISKTABL *dskentry);
extern void prtformat(DISKTABL *dskentry);
extern char *getfmt(short fmtcd);
extern void prtsecsiz(DISKTABL *dskentry);
extern int getsecsiz(FLOPDEV *flpentry);
