extern int getnum(short fldsiz, short *pdata);
extern int getstr(short fldsiz, char *pdata);
extern ushort getchr();
extern ushort getcntrl();
extern void movcur(char c, short maxcol, short maxlne);
extern void initcur(ushort stline, int nline, int stcol, int ncol, int colwids, ...);
extern void prtpos(ushort line, ushort col, char *format, ...);
extern void prtcnt(char *format, ...);
extern void currnt();
extern int prtmcur();
extern int prtcur(char *f);
extern void clmn();
extern void putwin(ushort linenum, char *strpt);
extern void prtwin(ushort linenum, char *format, ...);
