extern int setlptbl(char *filename);
extern void cpydrv(DRVTABL *drv1, DRVTABL *drv2);
extern void initlptbl(DRVTABL *drvtbl);
extern void prtlhd();
extern void prtdrlet();
extern void prtlptbl(DRVTABL *drvtbl);
extern int getlfld(DRVTABL *drvtbl);
extern void prtlmsg();
extern void tempfld(DRVTABL *drvtbl);
extern void schfld(DRVTABL *drvtbl);
extern void phyfld(DRVTABL *drvtbl);
extern void chkdrvtbl(DRVTABL *drvtbl);
extern void prtsord(byte *drvs);
extern char *sordstr(short scrnum);
extern void prttdrv(byte tdrv);
extern void prtpnum(byte *lptbl);
extern int prtstr(byte *lptbl);
extern void prtdup(byte *lptbl);
extern int searchdisk(ushort phydev);
